### ISSUE TITLE
Free Pascal?

### ISSUE THREAD

**Issue by cpicanco** [arthurprs/msgpack-delphi#2]
Trying to run the test on free-pascal-lazarus after an auto conversion of the project :

```
Compile Project, Target: test: Exit code 256, Errors: 1, Warnings: 6, Hints: 9
test.lpr(5,2) Note: APPTYPE is not supported by the target OS
msgpack.pas(37,2) Warning: Illegal identifier "UNSAFE_CAST" for $WARN directive
msgpack.pas(38,2) Warning: Illegal identifier "UNSAFE_CODE" for $WARN directive
msgpack.pas(39,2) Warning: Illegal identifier "UNSAFE_TYPE" for $WARN directive
msgpack.pas(40,2) Warning: Illegal identifier "HIDDEN_VIRTUAL" for $WARN directive
msgpack.pas(196,14) Warning: An inherited method is hidden by "Equals(const IMsgPackObject):Boolean;"
msgpack.pas(66,47) Hint: Parameter "Value" not used
msgpack.pas(851,42) Hint: Local variable "mapIt" of a managed type does not seem to be initialized
msgpack.pas(967,29) Hint: Function result variable does not seem to be initialized
msgpack.pas(972,29) Hint: Function result variable does not seem to be initialized
msgpack.pas(978,29) Hint: Function result variable does not seem to be initialized
msgpack.pas(990,30) Hint: Function result variable does not seem to be initialized
msgpack.pas(1065,38) Warning: Conversion between ordinals and pointers is not portable
msgpack.pas(1065,31) Error: Illegal type conversion: "Pointer" to "Single"
msgpack.pas(1228,42) Hint: Local variable "mapIt" of a managed type does not seem to be initialized
msgpack.pas(1341,44) Hint: Local variable "mapIt" of a managed type does not seem to be initialized

```

Any help would be appreciated.
Best regards,
Rafael

**Comment by cpicanco** [comment]
With FPC 3.0.0 and Lazarus 1.6.0

After deleting all `$WARN` directives and changing the following line:

```
    $CA: // float
      begin
        FType := mptFloat;
        FVariant.dataFloat :=  ReadBEDWord(); // Single(Pointer(ReadBEDWord()));  Line 1062
      end; 
```

Should I expect anything exploding? Test is passed though... need to test in real action.

**Comment by arthurprs** [comment]
I don't think thats safe as the cast will be made numerically instead of just reinterpreting the bytes.

I addressed both this bug and some compatibility improveyments in 8d29a96678a4b7a29c0e2f856c12ab940a3acdff Let me know if it works for you.

**Comment by cpicanco** [comment]
Thanks for this.

To avoid some warnings, if of any interest, I am sharing my notes on `implicit type conversion`:

From the FPC docs:

> **Warning: Implicit string type conversion from ”arg1” to ”arg2”**
>     An implicit type conversion from an ansi string type to an unicode string type is encountered. To avoid this warning perform an explicit type conversion. 

How to explicit type convert:

```
'key' + IntToStr(i);
'key' + WideString(IntToStr(i));
```

Some discussion on the topic [here](http://forum.lazarus.freepascal.org/index.php/topic,33413.msg216503.html#msg216503).

**Comment by cpicanco** [comment]
#3
